### ISSUE TITLE
I have a question - isn't Push Shift API killed by reddit recently ?

### ISSUE THREAD

**Issue by ReEnMikki** [Dragonatorul/reddit_imgur_archive#1]
I had been working on a similar project to scrape all imgur images in all comments/ posts of any reddit user, and I learned that reddit revoked Push Shift's access to reddit's API, and thus all Push Shift API methods no longer work for me. How is it working for you ?

https://www.reddit.com/r/modnews/comments/134tjpe/reddit_data_api_update_changes_to_pushshift_access/

**Comment by Dragonatorul** [comment]
You're right, the Pushshift API was revoked access to Reddit API, so it isn't viable for the most recent submissions, starting from when access was revoked. But it still has historical data going back to 2005. The Reddit API doesn't grant access to more than 1000 posts sorted by their sort method. 

Pushshift is still the best way I could find to get all the data, or most of it, since before their access was revoked. Or at least it worked last week when I used it to collect the data. 

I don't really care about the last couple of weeks, as much as the past few years of data.

**Comment by ReEnMikki** [comment]
So accessing very ancient stuffs is still possible with push shift ? When I tried pmaw with it I got this error: WARNING:pmaw.PushshiftAPIBase:Not all PushShift shards are active. Query results may be incomplete

Also, can your scraper scrape imgur links from comments of a reddit user instead of subreddits ? I really need to scrape those of a redditor before 15th May (imgur mass purge day) And he has like 90k images in total so of course reddit API is not viable

(my scraper still worked from like 4 days ago but just realized today it doesn't anymore, no matter the praw or pmaw for push shift)

**Comment by Dragonatorul** [comment]
It turns out Pushshift API is dead, at least for now. From the results they return it looks like they're being hammered and the elasticsearch instance is overloaded. Oops. I hope that's not my fault. 

```
"error": {
      "root_cause": [
        {
          "type": "es_rejected_execution_exception",
          "reason": "rejected execution of TimedRunnable{original=ActionRunnable#wrap[org.elasticsearch.search.SearchService$$Lambda$7235/0x000000080222a4d0@3a743fd9], creationTimeNanos=3541619306178486, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on EWMATrackingEsThreadPoolExecutor[name = ES-D-21-NCRI-VA/search, queue capacity = 1000, task execution EWMA = 44ms, org.elasticsearch.common.util.concurrent.EWMATrackingEsThreadPoolExecutor@32f45e15[Running, pool size = 25, active threads = 25, queued tasks = 1000, completed tasks = 259229797]]"
        },
[...]
"status": 429
```

As for the original question: no, it only searches submissions, not comments. That would have been way too time consuming.

**Comment by ReEnMikki** [comment]
The situation looks hopeless for imgur archivists. Damn it.
